### ISSUE TITLE
[학생수정,학생등록페이지] 사진 선택하고 넣어두어도 여전히 학생사진은 액박으로 남아있음

### ISSUE THREAD

**Issue by leepayi11** [paikwiki/prj-louvre#16]
![image](https://cloud.githubusercontent.com/assets/25189677/22049416/624a7650-dd76-11e6-97b1-c8d683d58023.png)

**Comment by paikwiki** [comment]
#24 이슈를 처리하면서 함께 처리했습니다. 사진을 수정할 수 없다는 문제가 아직 남아있지만 별도의 이슈로 등록하고 #16 은 닫도록 하겠습니다.
