### ISSUE TITLE
[학생수정 후 에러] 

### ISSUE THREAD

**Issue by leepayi11** [paikwiki/prj-louvre#17]
학생수정을 누르고 들어가 이름, 이메일등 정보를 바꾸고 나오면
기존에 등록해뒀던 프로필사진이 날라가고 액박으로 뜸. 

![image](https://cloud.githubusercontent.com/assets/25189677/22049491/dd2259b0-dd76-11e6-9f17-6da8dad6b1da.png)
![image](https://cloud.githubusercontent.com/assets/25189677/22049497/e81169e2-dd76-11e6-8cda-437660f0cd0b.png)

**Comment by paikwiki** [comment]
이 이슈도 #24 이슈를 처리하면서 #16 이슈와 함께 처리됐습니다.
